/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "callButton1": { "creationFunction": "CreateCallButton", "customImage": "Images/callGlyph.png", "customImagePosition": "PushButton.IMAGE_POSITION_NONE", "customImagePressed": "Images/callGlyph.png", "initialHeight": 32, "initialWidth": 253, "leftImageWidth": 6, "phoneNumber": "1-617-373-5320", "rightImageWidth": 6, "text": "Call The Pit" },
    "done": { "creationFunction": "CreatePushButton", "initialHeight": 23, "initialWidth": 57, "leftImageWidth": 5, "onclick": "flipToFront", "rightImageWidth": 5, "text": "Done" },
    "infoButton": { "creationFunction": "CreatePushButton", "customImage": "Images/info.png", "customImagePosition": "PushButton.IMAGE_POSITION_CENTER", "customImagePressed": "Images/info_pressed.png", "initialHeight": 35, "initialWidth": 36, "leftImageWidth": 1, "onclick": "flipToBack", "rightImageWidth": 1 },
    "mapButton1": { "address": "440 Huntington Avenue, Boston, MA", "creationFunction": "CreateMapButton", "customImage": "Images/mapGlyph.png", "customImagePosition": "PushButton.IMAGE_POSITION_NONE", "customImagePressed": "Images/mapGlyph.png", "initialHeight": 32, "initialWidth": 253, "leftImageWidth": 6, "onclick": "goToMaps", "rightImageWidth": 6, "text": "Find The Pit" },
    "new-pitcam": { "creationFunction": "CreatePushButton", "initialHeight": 45, "initialWidth": 223, "leftImageWidth": 23, "onclick": "gotoNew", "rightImageWidth": 23, "text": "NEW PITCAM" },
    "old-pitcam": { "creationFunction": "CreatePushButton", "initialHeight": 45, "initialWidth": 223, "leftImageWidth": 23, "onclick": "gotoOld", "rightImageWidth": 23, "text": "OLD PITCAM" },
    "pitcams": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "dissolve" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "dissolve" }] },
    "sides": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "flip" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "flip" }] },
    "viewer3000": { "creationFunction": "CreateText", "text": "Pitcam Viewer 3000" }
};
